name: New Catalog Entry
description: Add a row to the DDF Catalog
title: "[DDF Catalog Entry] : Please Copy Solution Name Here"
body:
  - type: markdown
    attributes:
      value: "# Instructions"

  - type: markdown
    attributes:
      value: |
        Please read the following instructions before submitting your solution
        
        1. Submit ONE form per solution, for clarity in the published catalog we do not want to have multiple solutions under a single line.
        
        2. Solution short descriptions will be truncated to the first 250 characters to preserve formatting in the published catalog. Please keep your short descriptions under 250 characters to avoid losing any information.
        
        3. Solution long descriptions will be stored on the unique page created for your solution; this is your opportunity to provide more context

        4. Descriptions for each of the prepopulated use cases are found below:
        * Data analytics and reporting - Solutions automating SAP set-up and statistical analysis
        * Data storage in Metadata Repository (MDR) - Solutions enabling data integration from/to an MDR
        * Decentralized Clinical Trials (DCT) - Solutions organizing and/or facilitating DCT set up and operation
        * Diverse and Inclusive Trial Design - Solutions capturing, displaying, and improving trial participant diversity
        * Electronic Data Capture (EDC) - Solutions integrating data from/to EDC systems
        * Electronic Health Record (EHR) - Solutions integrating data from/to EHR systems
        * eSource - Solutions utilizing data integration from non-standard sources (i.e. wearables, in home diagnostics, etc.)
        * Operational systems (i.e. CTMS, IRT, etc.) - Solutions integrating data from/to other operational systems
        * Patient eligibility screening - Solutions utilizing inclusion/exclusion criteria for the purposes of screening participants
        * Registry reporting - Solutions providing automated submission to data registries
        * Regulatory submission - Solutions providing automated submission to regulatory bodies
        * Risk management - ABC
        * Study authoring - Solutions used to design and publish a study protocol
        * Other use case(s) - If your solution is addressing a use case we do not currently capture, please list this in the "Other Use Case(s)" field for inclusion.
        
        5. Think of this catalog as a virtual brochure or business card which you would give to someone at an in-person event. It should contain enough information to inform them on your product and give an idea of where to reach out to continue the conversation.

        6. Please confirm the information is correct before submitting the form, once submitted it may be difficult to modify your submission with specific updates.
        
        If you have any questions, please reach out to DDF@transceleratebiopharmainc.com for further assistance.

  - type: input
    id: org_name
    attributes:
      label: Organization Name
      description: What is the name of your organization or team?
    validations:
      required: true
  
  - type: input
    id: solution_name
    attributes:
      label: Solution Name
      description: What is the name of your Digital Data Flow (DDF) compatible solution or platform?
    validations:
      required: true

  - type: input
    id: primary_contact_email
    attributes:
      label: Primary Point of Contact Email
      description: What is the primary point of contact email for your solution?
    validations:
      required: true

  - type: input
    id: secondary_contact_email
    attributes:
      label: Secondary Point of Contact Email
      description: What is the secondary point of contact email for your solution? (Optional)
    validations:
      required: false
  
  - type: textarea
    id: solution_short_desc
    attributes:
      label: Solution Short Description
      description: Please provide a short description of your solution (250 characters or less)
    validations:
      required: true

  - type: textarea
    id: solution_long_desc
    attributes:
      label: Solution Long Description
      description: Please describe your solution, making sure to include how it utilizes the Unified Study Definition Model (USDM), how it enables protocol digitization, and where it sits on the development lifecycle.
    validations:
      required: true

  - type: checkboxes
    id: use_cases
    attributes:
      label: Covered Use Cases
      description: Please select one or more of the following use cases which your solution enables.
      options:

        - label: Data analytics and reporting
        - label: Data storage in Metadata Repository (MDR)
        - label: Decentralized Clinical Trials (DCT)
        - label: 
        - label:
        - label: Diverse and Inclusive Trial Design
        - label: Electronic Data Capture (EDC)
        - label: Electronic Health Record (EHR)
        - label: eSource
        - label: Operational systems (i.e. CTMS, IRT, etc.)
        - label: Patient elegibility screening
        - label: Registry reporting
        - label: Regulatory submission
        - label: Risk management
        - label: Study authoring

  - type: textarea
    id: other_use_case
    attributes:
      label: Other Use Case(s)
      description: If not listed above, please enter your use case(s) below separated by a comma.
    validations:
      required: false

  - type: dropdown
    id: usdm_version
    attributes:
      label: USDM Version Compatibility
      description: What version of the USDM is your solution compatible with?
      multiple: false
      options:
        - "2.0"
        - "2.5"
        - "3.0"
      default: 0
    validations:
      required: true

  - type: input
    id: solution_link
    attributes:
      label: Link to Solution Website
      description: Provide a link to your solution website. (Optional)
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Legal Disclaimer"

  - type: markdown
    attributes:
      value: "By submitting this form, I recognize all information provided in the above form is provided under my own will and is not considered an endosement from TransCelerate or any of it's member companies. I certify all information entered is accurate to the best of my knowledge, and I am legally empowered to submit it."

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirm Submission?
      description: Check the box below to enable submission.
      options:
        - label: Confirm Submission
          required: true
