name: Update Directory

on:
  issues:
    types: [opened]

env:
  GITHUB_CONTEXT: ${{ toJson(github.event.issue) }}

jobs:
  update-directory:
    name: Update Directory
    if: contains(github.event.issue.labels.*.name, 'new-directory-entry')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Check-out python repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: 'directory'
        sparse-checkout-cone-mode: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check root file system
      run: |
        ls ${{ github.workspace }}

    - name: check directory
      run: |
        ls ${{ github.workspace }}/directory

    - name: Run add_row
      run: python ${{ github.workspace }}/directory/add_row.py
      shell: sh

    - name: Check git config
      run: |
        git config --list

    - name: Set config and commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ${{ github.workspace }}/directory/directory.md
        git commit -m "Adding Row from issue #${{ github.event.issue.number }} to Directory via Github Action"
    
    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}